
#define TEST_IOCTL_NUM 'z'
#define IOCTL_START_NUM 0x80

//define cmd
#define IOCTL_MSG_RECEIVE       IOCTL_START_NUM+1	
#define IOCTL_MSG_SEND		IOCTL_START_NUM+2	
#define IOCTL_CH_OPEN		IOCTL_START_NUM+3	
#define IOCTL_CH_CLOSE		IOCTL_START_NUM+4

#define MSG_RECEIVE		_IOWR(TEST_IOCTL_NUM, IOCTL_MSG_RECEIVE, void *)	
#define MSG_SEND		_IOWR(TEST_IOCTL_NUM, IOCTL_MSG_SEND, void *)	
#define CH_OPEN			_IOWR(TEST_IOCTL_NUM, IOCTL_CH_OPEN, void *)		
#define CH_CLOSE		_IOWR(TEST_IOCTL_NUM, IOCTL_CH_CLOSE, void *)



#define MAXMSG 5
#define MAXVOL 512
#define MSGSIZE 128
#define MAX_CHANNEL 5


